name: Fullbright
version: '${project.version}'
main: net.daechler.fullbright.Fullbright
api-version: 1.19
authors: [ Daechler ]
description: Add the fullbright effect to a player.
commands:
  fullbright:
    description: Add the fullbright effect to a player.
    usage: /fullbright
    permission: fullbright.use
    aliases: fb